---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: gluster
spec:
  template:
    metadata:
      name: gluster
      labels:
        app: gluster
    spec:
      nodeSelector:
        node: storage
      containers:
      - name: glusterd
        image: jaohaohsuan/gluster-docker:3.7.18
        imagePullPolicy: IfNotPresent
        args: ["/build/entrypoint.sh"]
        env:
          - name: TERM
            value: xterm
        ports:
        - containerPort: 24007
        volumeMounts:
        - name: devtree
          mountPath: "/dev"
        - name: glusterfs-etc
          mountPath: "/etc/glusterfs"
        - name: glusterfs-logs
          mountPath: "/var/log/glusterfs"
        - name: glusterfs-config
          mountPath: "/var/lib/glusterd"
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: devtree
        hostPath:
          path: "/dev"
      - name: glusterfs-etc
        hostPath:
          path: "/etc/glusterfs"
      - name: glusterfs-logs
        hostPath:
          path: "/var/log/glusterfs"
      - name: glusterfs-config
        hostPath:
          path: "/var/lib/glusterd"
